# Generated by Django 3.1 on 2020-08-29 10:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_sr_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=10)),
                ('vendor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_sr_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=10)),
                ('total_price', models.FloatField(max_length=10)),
                ('delete_product', models.BooleanField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_app.invoice')),
            ],
        ),
    ]
